name: Release

on:
  push:
    tags:
      - "v*" # Push tags matching 'v*', e.g., v1.0.0

env:
  PROJECT_NAME: rust_project_arena # 定义项目名称变量

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: aarch64-linux-android
            use_cross: true # 标记使用 cross 工具
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Install cross (if needed)
        if: matrix.use_cross
        run: cargo install cross

      - name: Build the project
        shell: bash
        run: |
          if [ "${{ matrix.use_cross }}" == "true" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Package the binary
        shell: bash
        run: |
          mkdir -p release
          binary_name="${{ env.PROJECT_NAME }}"
          if [ "${{ matrix.target }}" == "x86_64-pc-windows-msvc" ]; then
            binary_name="$binary_name.exe"
          fi
          cp target/${{ matrix.target }}/release/$binary_name release/
          echo "Binary packaged: release/$binary_name"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.target }}
          path: release/

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Debug artifacts directory
        run: ls -R artifacts # 调试：列出 artifacts 目录内容

      - name: Extract version from tag
        id: extract_version
        run: |
          version=${GITHUB_REF#refs/tags/}
          echo "Extracted version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get current date
        id: get_date
        run: |
          current_date=$(date -u +"%Y-%m-%d")
          echo "Current date: $current_date"
          echo "date=$current_date" >> $GITHUB_OUTPUT

      - name: Create Release via GitHub API
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=${GITHUB_REF#refs/tags/}
          release_name="Release $tag_name"
          response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
            -d "{
              \"tag_name\": \"$tag_name\",
              \"name\": \"$release_name\",
              \"draft\": false,
              \"prerelease\": false
            }")
          if [ -z "$(echo "$response" | jq -r '.upload_url')" ]; then
            echo "Failed to create release"
            exit 1
          fi
          upload_url=$(echo "$response" | jq -r '.upload_url' | sed 's/{.*}//')
          echo "upload_url=$upload_url" >> $GITHUB_OUTPUT

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          upload_url=${{ steps.create_release.outputs.upload_url }}
          for target in x86_64-unknown-linux-gnu x86_64-pc-windows-msvc x86_64-apple-darwin aarch64-apple-darwin aarch64-linux-android; do
            if [ "$target" == "x86_64-pc-windows-msvc" ]; then
              asset_path="artifacts/${{ env.PROJECT_NAME }}-$target/${{ env.PROJECT_NAME }}.exe"
              asset_name="${{ env.PROJECT_NAME }}-${{ steps.extract_version.outputs.version }}-${{ steps.get_date.outputs.date }}-$target.exe"
            else
              asset_path="artifacts/${{ env.PROJECT_NAME }}-$target/${{ env.PROJECT_NAME }}"
              asset_name="${{ env.PROJECT_NAME }}-${{ steps.extract_version.outputs.version }}-${{ steps.get_date.outputs.date }}-$target"
            fi

            if [ -f "$asset_path" ]; then
              echo "Uploading $asset_path as $asset_name"
              curl -s -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: application/octet-stream" \
                --data-binary @$asset_path \
                "$upload_url?name=$asset_name"
            else
              echo "Warning: File $asset_path does not exist. Skipping upload for $target."
            fi
          done
